// BC-P1 站点契约。站点树（BP-01 §2.2 Site 为行业中性的核心空间概念）；
// 移动站点时禁止形成环（MoveSite 循环依赖拒绝是领域规则测试点）。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: site/v1/site.proto

package sitev1

import (
	v1 "github.com/jsl-aiot/platform/api/common/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Site 站点聚合：厂区 / 单体楼 / 农场 / 院区 / 防护点位群的统一抽象。
type Site struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	SiteId   string                 `protobuf:"bytes,1,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	TenantId string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// 父站点，为空表示租户根站点。
	ParentSiteId string `protobuf:"bytes,3,opt,name=parent_site_id,json=parentSiteId,proto3" json:"parent_site_id,omitempty"`
	// 租户内唯一。
	Name        string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName string `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// 行业语义类型（如 factory/building/farm/campus/guard_point），由行业模块扩展。
	SiteType      string          `protobuf:"bytes,6,opt,name=site_type,json=siteType,proto3" json:"site_type,omitempty"`
	Audit         *v1.AuditFields `protobuf:"bytes,7,opt,name=audit,proto3" json:"audit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Site) Reset() {
	*x = Site{}
	mi := &file_site_v1_site_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Site) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Site) ProtoMessage() {}

func (x *Site) ProtoReflect() protoreflect.Message {
	mi := &file_site_v1_site_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Site.ProtoReflect.Descriptor instead.
func (*Site) Descriptor() ([]byte, []int) {
	return file_site_v1_site_proto_rawDescGZIP(), []int{0}
}

func (x *Site) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

func (x *Site) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Site) GetParentSiteId() string {
	if x != nil {
		return x.ParentSiteId
	}
	return ""
}

func (x *Site) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Site) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Site) GetSiteType() string {
	if x != nil {
		return x.SiteType
	}
	return ""
}

func (x *Site) GetAudit() *v1.AuditFields {
	if x != nil {
		return x.Audit
	}
	return nil
}

type CreateSiteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentSiteId  string                 `protobuf:"bytes,1,opt,name=parent_site_id,json=parentSiteId,proto3" json:"parent_site_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	SiteType      string                 `protobuf:"bytes,4,opt,name=site_type,json=siteType,proto3" json:"site_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSiteRequest) Reset() {
	*x = CreateSiteRequest{}
	mi := &file_site_v1_site_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSiteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSiteRequest) ProtoMessage() {}

func (x *CreateSiteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_site_v1_site_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSiteRequest.ProtoReflect.Descriptor instead.
func (*CreateSiteRequest) Descriptor() ([]byte, []int) {
	return file_site_v1_site_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSiteRequest) GetParentSiteId() string {
	if x != nil {
		return x.ParentSiteId
	}
	return ""
}

func (x *CreateSiteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSiteRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CreateSiteRequest) GetSiteType() string {
	if x != nil {
		return x.SiteType
	}
	return ""
}

type GetSiteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SiteId        string                 `protobuf:"bytes,1,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSiteRequest) Reset() {
	*x = GetSiteRequest{}
	mi := &file_site_v1_site_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSiteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSiteRequest) ProtoMessage() {}

func (x *GetSiteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_site_v1_site_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSiteRequest.ProtoReflect.Descriptor instead.
func (*GetSiteRequest) Descriptor() ([]byte, []int) {
	return file_site_v1_site_proto_rawDescGZIP(), []int{2}
}

func (x *GetSiteRequest) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

type ListSitesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *v1.PageRequest        `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSitesRequest) Reset() {
	*x = ListSitesRequest{}
	mi := &file_site_v1_site_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSitesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSitesRequest) ProtoMessage() {}

func (x *ListSitesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_site_v1_site_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSitesRequest.ProtoReflect.Descriptor instead.
func (*ListSitesRequest) Descriptor() ([]byte, []int) {
	return file_site_v1_site_proto_rawDescGZIP(), []int{3}
}

func (x *ListSitesRequest) GetPage() *v1.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListSitesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sites         []*Site                `protobuf:"bytes,1,rep,name=sites,proto3" json:"sites,omitempty"`
	Page          *v1.PageResponse       `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSitesResponse) Reset() {
	*x = ListSitesResponse{}
	mi := &file_site_v1_site_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSitesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSitesResponse) ProtoMessage() {}

func (x *ListSitesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_site_v1_site_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSitesResponse.ProtoReflect.Descriptor instead.
func (*ListSitesResponse) Descriptor() ([]byte, []int) {
	return file_site_v1_site_proto_rawDescGZIP(), []int{4}
}

func (x *ListSitesResponse) GetSites() []*Site {
	if x != nil {
		return x.Sites
	}
	return nil
}

func (x *ListSitesResponse) GetPage() *v1.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type UpdateSiteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SiteId        string                 `protobuf:"bytes,1,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	SiteType      string                 `protobuf:"bytes,3,opt,name=site_type,json=siteType,proto3" json:"site_type,omitempty"`
	Version       int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSiteRequest) Reset() {
	*x = UpdateSiteRequest{}
	mi := &file_site_v1_site_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSiteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSiteRequest) ProtoMessage() {}

func (x *UpdateSiteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_site_v1_site_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSiteRequest.ProtoReflect.Descriptor instead.
func (*UpdateSiteRequest) Descriptor() ([]byte, []int) {
	return file_site_v1_site_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateSiteRequest) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

func (x *UpdateSiteRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UpdateSiteRequest) GetSiteType() string {
	if x != nil {
		return x.SiteType
	}
	return ""
}

func (x *UpdateSiteRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type MoveSiteRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	SiteId string                 `protobuf:"bytes,1,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	// 新父站点；为空表示移动到租户根。
	NewParentSiteId string `protobuf:"bytes,2,opt,name=new_parent_site_id,json=newParentSiteId,proto3" json:"new_parent_site_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MoveSiteRequest) Reset() {
	*x = MoveSiteRequest{}
	mi := &file_site_v1_site_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveSiteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveSiteRequest) ProtoMessage() {}

func (x *MoveSiteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_site_v1_site_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveSiteRequest.ProtoReflect.Descriptor instead.
func (*MoveSiteRequest) Descriptor() ([]byte, []int) {
	return file_site_v1_site_proto_rawDescGZIP(), []int{6}
}

func (x *MoveSiteRequest) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

func (x *MoveSiteRequest) GetNewParentSiteId() string {
	if x != nil {
		return x.NewParentSiteId
	}
	return ""
}

var File_site_v1_site_proto protoreflect.FileDescriptor

const file_site_v1_site_proto_rawDesc = "" +
	"\n" +
	"\x12site/v1/site.proto\x12\x14jsl.platform.site.v1\x1a\x16common/v1/common.proto\x1a\x1cgoogle/api/annotations.proto\"\xf1\x01\n" +
	"\x04Site\x12\x17\n" +
	"\asite_id\x18\x01 \x01(\tR\x06siteId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12$\n" +
	"\x0eparent_site_id\x18\x03 \x01(\tR\fparentSiteId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x05 \x01(\tR\vdisplayName\x12\x1b\n" +
	"\tsite_type\x18\x06 \x01(\tR\bsiteType\x129\n" +
	"\x05audit\x18\a \x01(\v2#.jsl.platform.common.v1.AuditFieldsR\x05audit\"\x8d\x01\n" +
	"\x11CreateSiteRequest\x12$\n" +
	"\x0eparent_site_id\x18\x01 \x01(\tR\fparentSiteId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x1b\n" +
	"\tsite_type\x18\x04 \x01(\tR\bsiteType\")\n" +
	"\x0eGetSiteRequest\x12\x17\n" +
	"\asite_id\x18\x01 \x01(\tR\x06siteId\"K\n" +
	"\x10ListSitesRequest\x127\n" +
	"\x04page\x18\x01 \x01(\v2#.jsl.platform.common.v1.PageRequestR\x04page\"\x7f\n" +
	"\x11ListSitesResponse\x120\n" +
	"\x05sites\x18\x01 \x03(\v2\x1a.jsl.platform.site.v1.SiteR\x05sites\x128\n" +
	"\x04page\x18\x02 \x01(\v2$.jsl.platform.common.v1.PageResponseR\x04page\"\x86\x01\n" +
	"\x11UpdateSiteRequest\x12\x17\n" +
	"\asite_id\x18\x01 \x01(\tR\x06siteId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x1b\n" +
	"\tsite_type\x18\x03 \x01(\tR\bsiteType\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\"W\n" +
	"\x0fMoveSiteRequest\x12\x17\n" +
	"\asite_id\x18\x01 \x01(\tR\x06siteId\x12+\n" +
	"\x12new_parent_site_id\x18\x02 \x01(\tR\x0fnewParentSiteId2\xb8\x04\n" +
	"\vSiteService\x12g\n" +
	"\n" +
	"CreateSite\x12'.jsl.platform.site.v1.CreateSiteRequest\x1a\x1a.jsl.platform.site.v1.Site\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/sites\x12h\n" +
	"\aGetSite\x12$.jsl.platform.site.v1.GetSiteRequest\x1a\x1a.jsl.platform.site.v1.Site\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/sites/{site_id}\x12o\n" +
	"\tListSites\x12&.jsl.platform.site.v1.ListSitesRequest\x1a'.jsl.platform.site.v1.ListSitesResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/sites\x12q\n" +
	"\n" +
	"UpdateSite\x12'.jsl.platform.site.v1.UpdateSiteRequest\x1a\x1a.jsl.platform.site.v1.Site\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*2\x13/v1/sites/{site_id}\x12r\n" +
	"\bMoveSite\x12%.jsl.platform.site.v1.MoveSiteRequest\x1a\x1a.jsl.platform.site.v1.Site\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/sites/{site_id}:moveB1Z/github.com/jsl-aiot/platform/api/site/v1;sitev1b\x06proto3"

var (
	file_site_v1_site_proto_rawDescOnce sync.Once
	file_site_v1_site_proto_rawDescData []byte
)

func file_site_v1_site_proto_rawDescGZIP() []byte {
	file_site_v1_site_proto_rawDescOnce.Do(func() {
		file_site_v1_site_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_site_v1_site_proto_rawDesc), len(file_site_v1_site_proto_rawDesc)))
	})
	return file_site_v1_site_proto_rawDescData
}

var file_site_v1_site_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_site_v1_site_proto_goTypes = []any{
	(*Site)(nil),              // 0: jsl.platform.site.v1.Site
	(*CreateSiteRequest)(nil), // 1: jsl.platform.site.v1.CreateSiteRequest
	(*GetSiteRequest)(nil),    // 2: jsl.platform.site.v1.GetSiteRequest
	(*ListSitesRequest)(nil),  // 3: jsl.platform.site.v1.ListSitesRequest
	(*ListSitesResponse)(nil), // 4: jsl.platform.site.v1.ListSitesResponse
	(*UpdateSiteRequest)(nil), // 5: jsl.platform.site.v1.UpdateSiteRequest
	(*MoveSiteRequest)(nil),   // 6: jsl.platform.site.v1.MoveSiteRequest
	(*v1.AuditFields)(nil),    // 7: jsl.platform.common.v1.AuditFields
	(*v1.PageRequest)(nil),    // 8: jsl.platform.common.v1.PageRequest
	(*v1.PageResponse)(nil),   // 9: jsl.platform.common.v1.PageResponse
}
var file_site_v1_site_proto_depIdxs = []int32{
	7, // 0: jsl.platform.site.v1.Site.audit:type_name -> jsl.platform.common.v1.AuditFields
	8, // 1: jsl.platform.site.v1.ListSitesRequest.page:type_name -> jsl.platform.common.v1.PageRequest
	0, // 2: jsl.platform.site.v1.ListSitesResponse.sites:type_name -> jsl.platform.site.v1.Site
	9, // 3: jsl.platform.site.v1.ListSitesResponse.page:type_name -> jsl.platform.common.v1.PageResponse
	1, // 4: jsl.platform.site.v1.SiteService.CreateSite:input_type -> jsl.platform.site.v1.CreateSiteRequest
	2, // 5: jsl.platform.site.v1.SiteService.GetSite:input_type -> jsl.platform.site.v1.GetSiteRequest
	3, // 6: jsl.platform.site.v1.SiteService.ListSites:input_type -> jsl.platform.site.v1.ListSitesRequest
	5, // 7: jsl.platform.site.v1.SiteService.UpdateSite:input_type -> jsl.platform.site.v1.UpdateSiteRequest
	6, // 8: jsl.platform.site.v1.SiteService.MoveSite:input_type -> jsl.platform.site.v1.MoveSiteRequest
	0, // 9: jsl.platform.site.v1.SiteService.CreateSite:output_type -> jsl.platform.site.v1.Site
	0, // 10: jsl.platform.site.v1.SiteService.GetSite:output_type -> jsl.platform.site.v1.Site
	4, // 11: jsl.platform.site.v1.SiteService.ListSites:output_type -> jsl.platform.site.v1.ListSitesResponse
	0, // 12: jsl.platform.site.v1.SiteService.UpdateSite:output_type -> jsl.platform.site.v1.Site
	0, // 13: jsl.platform.site.v1.SiteService.MoveSite:output_type -> jsl.platform.site.v1.Site
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_site_v1_site_proto_init() }
func file_site_v1_site_proto_init() {
	if File_site_v1_site_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_site_v1_site_proto_rawDesc), len(file_site_v1_site_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_site_v1_site_proto_goTypes,
		DependencyIndexes: file_site_v1_site_proto_depIdxs,
		MessageInfos:      file_site_v1_site_proto_msgTypes,
	}.Build()
	File_site_v1_site_proto = out.File
	file_site_v1_site_proto_goTypes = nil
	file_site_v1_site_proto_depIdxs = nil
}
