// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v3.0.0
// - protoc             (unknown)
// source: site/v1/site.proto

package sitev1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationSiteServiceCreateSite = "/jsl.platform.site.v1.SiteService/CreateSite"
const OperationSiteServiceGetSite = "/jsl.platform.site.v1.SiteService/GetSite"
const OperationSiteServiceListSites = "/jsl.platform.site.v1.SiteService/ListSites"
const OperationSiteServiceMoveSite = "/jsl.platform.site.v1.SiteService/MoveSite"
const OperationSiteServiceUpdateSite = "/jsl.platform.site.v1.SiteService/UpdateSite"

type SiteServiceHTTPServer interface {
	CreateSite(context.Context, *CreateSiteRequest) (*Site, error)
	GetSite(context.Context, *GetSiteRequest) (*Site, error)
	ListSites(context.Context, *ListSitesRequest) (*ListSitesResponse, error)
	// MoveSite MoveSite 移动站点子树；目标父站点不得是自身或自身后代（循环依赖拒绝）。
	MoveSite(context.Context, *MoveSiteRequest) (*Site, error)
	UpdateSite(context.Context, *UpdateSiteRequest) (*Site, error)
}

func RegisterSiteServiceHTTPServer(s *http.Server, srv SiteServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/v1/sites", _SiteService_CreateSite0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/sites/{site_id}", _SiteService_GetSite0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/sites", _SiteService_ListSites0_HTTP_Handler(srv))
	r.Handle("PATCH", "/v1/sites/{site_id}", _SiteService_UpdateSite0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/sites/{site_id}:move", _SiteService_MoveSite0_HTTP_Handler(srv))
}

func _SiteService_CreateSite0_HTTP_Handler(srv SiteServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateSiteRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSiteServiceCreateSite)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateSite(ctx, req.(*CreateSiteRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Site)
		return ctx.Result(200, reply)
	}
}

func _SiteService_GetSite0_HTTP_Handler(srv SiteServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSiteRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSiteServiceGetSite)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSite(ctx, req.(*GetSiteRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Site)
		return ctx.Result(200, reply)
	}
}

func _SiteService_ListSites0_HTTP_Handler(srv SiteServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListSitesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSiteServiceListSites)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSites(ctx, req.(*ListSitesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListSitesResponse)
		return ctx.Result(200, reply)
	}
}

func _SiteService_UpdateSite0_HTTP_Handler(srv SiteServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateSiteRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSiteServiceUpdateSite)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateSite(ctx, req.(*UpdateSiteRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Site)
		return ctx.Result(200, reply)
	}
}

func _SiteService_MoveSite0_HTTP_Handler(srv SiteServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in MoveSiteRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSiteServiceMoveSite)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.MoveSite(ctx, req.(*MoveSiteRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Site)
		return ctx.Result(200, reply)
	}
}

type SiteServiceHTTPClient interface {
	CreateSite(ctx context.Context, req *CreateSiteRequest, opts ...http.CallOption) (rsp *Site, err error)
	GetSite(ctx context.Context, req *GetSiteRequest, opts ...http.CallOption) (rsp *Site, err error)
	ListSites(ctx context.Context, req *ListSitesRequest, opts ...http.CallOption) (rsp *ListSitesResponse, err error)
	// MoveSite MoveSite 移动站点子树；目标父站点不得是自身或自身后代（循环依赖拒绝）。
	MoveSite(ctx context.Context, req *MoveSiteRequest, opts ...http.CallOption) (rsp *Site, err error)
	UpdateSite(ctx context.Context, req *UpdateSiteRequest, opts ...http.CallOption) (rsp *Site, err error)
}

type SiteServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewSiteServiceHTTPClient(client *http.Client) SiteServiceHTTPClient {
	return &SiteServiceHTTPClientImpl{client}
}

func (c *SiteServiceHTTPClientImpl) CreateSite(ctx context.Context, in *CreateSiteRequest, opts ...http.CallOption) (*Site, error) {
	var out Site
	pattern := "/v1/sites"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationSiteServiceCreateSite),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SiteServiceHTTPClientImpl) GetSite(ctx context.Context, in *GetSiteRequest, opts ...http.CallOption) (*Site, error) {
	var out Site
	pattern := "/v1/sites/{site_id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSiteServiceGetSite),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SiteServiceHTTPClientImpl) ListSites(ctx context.Context, in *ListSitesRequest, opts ...http.CallOption) (*ListSitesResponse, error) {
	var out ListSitesResponse
	pattern := "/v1/sites"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSiteServiceListSites),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// MoveSite MoveSite 移动站点子树；目标父站点不得是自身或自身后代（循环依赖拒绝）。
func (c *SiteServiceHTTPClientImpl) MoveSite(ctx context.Context, in *MoveSiteRequest, opts ...http.CallOption) (*Site, error) {
	var out Site
	pattern := "/v1/sites/{site_id}:move"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationSiteServiceMoveSite),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SiteServiceHTTPClientImpl) UpdateSite(ctx context.Context, in *UpdateSiteRequest, opts ...http.CallOption) (*Site, error) {
	var out Site
	pattern := "/v1/sites/{site_id}"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationSiteServiceUpdateSite),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
