// 平台统一事件信封与载荷（ADR-0005）。
// 决策：payload 直接嵌入 oneof（编译期类型安全 + buf breaking 覆盖载荷字段），
// 不采用 Any 包装。新增事件 = 追加 oneof 成员（向后兼容）；
// 禁止修改既有字段的编号与类型。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: events/v1/envelope.proto

package eventsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventEnvelope 平台统一事件信封。
type EventEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 事件唯一标识（ULID，时间有序）。
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// 事件类型名，如 "platform.tenant.provisioned"（与 oneof 成员一一对应）。
	EventType string `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// 载荷 schema 版本（信封本身不变式；载荷演进走 buf breaking 门禁）。
	SchemaVersion string `protobuf:"bytes,3,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	// 归属链（BP-03 §4.1）：tenant → org → site。
	TenantId string `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	OrgId    string `protobuf:"bytes,5,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	SiteId   string `protobuf:"bytes,6,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	// 事件发生时间（领域时间，非投递时间）。
	OccurredAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	// W3C Trace ID（跨域链路追踪）。
	TraceId string `protobuf:"bytes,8,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// 事件来源 BC 标识，如 "bc-p1"。
	Source string `protobuf:"bytes,9,opt,name=source,proto3" json:"source,omitempty"`
	// Types that are valid to be assigned to Events:
	//
	//	*EventEnvelope_TenantProvisioned
	//	*EventEnvelope_TenantSuspended
	//	*EventEnvelope_TenantReactivated
	//	*EventEnvelope_TenantDeactivated
	//	*EventEnvelope_SiteCreated
	//	*EventEnvelope_IndustryAssemblyBound
	Events        isEventEnvelope_Events `protobuf_oneof:"events"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventEnvelope) Reset() {
	*x = EventEnvelope{}
	mi := &file_events_v1_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEnvelope) ProtoMessage() {}

func (x *EventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEnvelope.ProtoReflect.Descriptor instead.
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return file_events_v1_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *EventEnvelope) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EventEnvelope) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EventEnvelope) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *EventEnvelope) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *EventEnvelope) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *EventEnvelope) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

func (x *EventEnvelope) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *EventEnvelope) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *EventEnvelope) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *EventEnvelope) GetEvents() isEventEnvelope_Events {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *EventEnvelope) GetTenantProvisioned() *TenantProvisioned {
	if x != nil {
		if x, ok := x.Events.(*EventEnvelope_TenantProvisioned); ok {
			return x.TenantProvisioned
		}
	}
	return nil
}

func (x *EventEnvelope) GetTenantSuspended() *TenantSuspended {
	if x != nil {
		if x, ok := x.Events.(*EventEnvelope_TenantSuspended); ok {
			return x.TenantSuspended
		}
	}
	return nil
}

func (x *EventEnvelope) GetTenantReactivated() *TenantReactivated {
	if x != nil {
		if x, ok := x.Events.(*EventEnvelope_TenantReactivated); ok {
			return x.TenantReactivated
		}
	}
	return nil
}

func (x *EventEnvelope) GetTenantDeactivated() *TenantDeactivated {
	if x != nil {
		if x, ok := x.Events.(*EventEnvelope_TenantDeactivated); ok {
			return x.TenantDeactivated
		}
	}
	return nil
}

func (x *EventEnvelope) GetSiteCreated() *SiteCreated {
	if x != nil {
		if x, ok := x.Events.(*EventEnvelope_SiteCreated); ok {
			return x.SiteCreated
		}
	}
	return nil
}

func (x *EventEnvelope) GetIndustryAssemblyBound() *IndustryAssemblyBound {
	if x != nil {
		if x, ok := x.Events.(*EventEnvelope_IndustryAssemblyBound); ok {
			return x.IndustryAssemblyBound
		}
	}
	return nil
}

type isEventEnvelope_Events interface {
	isEventEnvelope_Events()
}

type EventEnvelope_TenantProvisioned struct {
	TenantProvisioned *TenantProvisioned `protobuf:"bytes,20,opt,name=tenant_provisioned,json=tenantProvisioned,proto3,oneof"`
}

type EventEnvelope_TenantSuspended struct {
	TenantSuspended *TenantSuspended `protobuf:"bytes,21,opt,name=tenant_suspended,json=tenantSuspended,proto3,oneof"`
}

type EventEnvelope_TenantReactivated struct {
	TenantReactivated *TenantReactivated `protobuf:"bytes,22,opt,name=tenant_reactivated,json=tenantReactivated,proto3,oneof"`
}

type EventEnvelope_TenantDeactivated struct {
	TenantDeactivated *TenantDeactivated `protobuf:"bytes,23,opt,name=tenant_deactivated,json=tenantDeactivated,proto3,oneof"`
}

type EventEnvelope_SiteCreated struct {
	SiteCreated *SiteCreated `protobuf:"bytes,24,opt,name=site_created,json=siteCreated,proto3,oneof"`
}

type EventEnvelope_IndustryAssemblyBound struct {
	IndustryAssemblyBound *IndustryAssemblyBound `protobuf:"bytes,25,opt,name=industry_assembly_bound,json=industryAssemblyBound,proto3,oneof"`
}

func (*EventEnvelope_TenantProvisioned) isEventEnvelope_Events() {}

func (*EventEnvelope_TenantSuspended) isEventEnvelope_Events() {}

func (*EventEnvelope_TenantReactivated) isEventEnvelope_Events() {}

func (*EventEnvelope_TenantDeactivated) isEventEnvelope_Events() {}

func (*EventEnvelope_SiteCreated) isEventEnvelope_Events() {}

func (*EventEnvelope_IndustryAssemblyBound) isEventEnvelope_Events() {}

// TenantProvisioned 租户开通完成（含装配记录、根组织、根站点初始化）。
type TenantProvisioned struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PlanId         string                 `protobuf:"bytes,3,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	IsolationLevel string                 `protobuf:"bytes,4,opt,name=isolation_level,json=isolationLevel,proto3" json:"isolation_level,omitempty"`
	// 随开通装配的行业模块 ID 列表。
	IndustryModules []string `protobuf:"bytes,5,rep,name=industry_modules,json=industryModules,proto3" json:"industry_modules,omitempty"`
	RootOrgId       string   `protobuf:"bytes,6,opt,name=root_org_id,json=rootOrgId,proto3" json:"root_org_id,omitempty"`
	RootSiteId      string   `protobuf:"bytes,7,opt,name=root_site_id,json=rootSiteId,proto3" json:"root_site_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TenantProvisioned) Reset() {
	*x = TenantProvisioned{}
	mi := &file_events_v1_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantProvisioned) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantProvisioned) ProtoMessage() {}

func (x *TenantProvisioned) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantProvisioned.ProtoReflect.Descriptor instead.
func (*TenantProvisioned) Descriptor() ([]byte, []int) {
	return file_events_v1_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *TenantProvisioned) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TenantProvisioned) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TenantProvisioned) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *TenantProvisioned) GetIsolationLevel() string {
	if x != nil {
		return x.IsolationLevel
	}
	return ""
}

func (x *TenantProvisioned) GetIndustryModules() []string {
	if x != nil {
		return x.IndustryModules
	}
	return nil
}

func (x *TenantProvisioned) GetRootOrgId() string {
	if x != nil {
		return x.RootOrgId
	}
	return ""
}

func (x *TenantProvisioned) GetRootSiteId() string {
	if x != nil {
		return x.RootSiteId
	}
	return ""
}

// TenantSuspended 租户被冻结（写冻结）。
type TenantSuspended struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantSuspended) Reset() {
	*x = TenantSuspended{}
	mi := &file_events_v1_envelope_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantSuspended) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantSuspended) ProtoMessage() {}

func (x *TenantSuspended) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_envelope_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantSuspended.ProtoReflect.Descriptor instead.
func (*TenantSuspended) Descriptor() ([]byte, []int) {
	return file_events_v1_envelope_proto_rawDescGZIP(), []int{2}
}

func (x *TenantSuspended) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TenantSuspended) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// TenantReactivated 租户从冻结恢复。
type TenantReactivated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantReactivated) Reset() {
	*x = TenantReactivated{}
	mi := &file_events_v1_envelope_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantReactivated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantReactivated) ProtoMessage() {}

func (x *TenantReactivated) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_envelope_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantReactivated.ProtoReflect.Descriptor instead.
func (*TenantReactivated) Descriptor() ([]byte, []int) {
	return file_events_v1_envelope_proto_rawDescGZIP(), []int{3}
}

func (x *TenantReactivated) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// TenantDeactivated 租户注销（仅可自 Suspended 进入；保留期后物理清理）。
type TenantDeactivated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantDeactivated) Reset() {
	*x = TenantDeactivated{}
	mi := &file_events_v1_envelope_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantDeactivated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantDeactivated) ProtoMessage() {}

func (x *TenantDeactivated) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_envelope_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantDeactivated.ProtoReflect.Descriptor instead.
func (*TenantDeactivated) Descriptor() ([]byte, []int) {
	return file_events_v1_envelope_proto_rawDescGZIP(), []int{4}
}

func (x *TenantDeactivated) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TenantDeactivated) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// SiteCreated 站点创建（含根站点初始化）。
type SiteCreated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SiteId        string                 `protobuf:"bytes,1,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ParentSiteId  string                 `protobuf:"bytes,3,opt,name=parent_site_id,json=parentSiteId,proto3" json:"parent_site_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SiteCreated) Reset() {
	*x = SiteCreated{}
	mi := &file_events_v1_envelope_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SiteCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteCreated) ProtoMessage() {}

func (x *SiteCreated) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_envelope_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteCreated.ProtoReflect.Descriptor instead.
func (*SiteCreated) Descriptor() ([]byte, []int) {
	return file_events_v1_envelope_proto_rawDescGZIP(), []int{5}
}

func (x *SiteCreated) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

func (x *SiteCreated) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SiteCreated) GetParentSiteId() string {
	if x != nil {
		return x.ParentSiteId
	}
	return ""
}

func (x *SiteCreated) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// IndustryAssemblyBound 行业模块装配绑定。
type IndustryAssemblyBound struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ModuleId      string                 `protobuf:"bytes,2,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	ModuleVersion string                 `protobuf:"bytes,3,opt,name=module_version,json=moduleVersion,proto3" json:"module_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndustryAssemblyBound) Reset() {
	*x = IndustryAssemblyBound{}
	mi := &file_events_v1_envelope_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndustryAssemblyBound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndustryAssemblyBound) ProtoMessage() {}

func (x *IndustryAssemblyBound) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_envelope_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndustryAssemblyBound.ProtoReflect.Descriptor instead.
func (*IndustryAssemblyBound) Descriptor() ([]byte, []int) {
	return file_events_v1_envelope_proto_rawDescGZIP(), []int{6}
}

func (x *IndustryAssemblyBound) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *IndustryAssemblyBound) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

func (x *IndustryAssemblyBound) GetModuleVersion() string {
	if x != nil {
		return x.ModuleVersion
	}
	return ""
}

var File_events_v1_envelope_proto protoreflect.FileDescriptor

const file_events_v1_envelope_proto_rawDesc = "" +
	"\n" +
	"\x18events/v1/envelope.proto\x12\x16jsl.platform.events.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd4\x06\n" +
	"\rEventEnvelope\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12%\n" +
	"\x0eschema_version\x18\x03 \x01(\tR\rschemaVersion\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\x12\x15\n" +
	"\x06org_id\x18\x05 \x01(\tR\x05orgId\x12\x17\n" +
	"\asite_id\x18\x06 \x01(\tR\x06siteId\x12;\n" +
	"\voccurred_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x19\n" +
	"\btrace_id\x18\b \x01(\tR\atraceId\x12\x16\n" +
	"\x06source\x18\t \x01(\tR\x06source\x12Z\n" +
	"\x12tenant_provisioned\x18\x14 \x01(\v2).jsl.platform.events.v1.TenantProvisionedH\x00R\x11tenantProvisioned\x12T\n" +
	"\x10tenant_suspended\x18\x15 \x01(\v2'.jsl.platform.events.v1.TenantSuspendedH\x00R\x0ftenantSuspended\x12Z\n" +
	"\x12tenant_reactivated\x18\x16 \x01(\v2).jsl.platform.events.v1.TenantReactivatedH\x00R\x11tenantReactivated\x12Z\n" +
	"\x12tenant_deactivated\x18\x17 \x01(\v2).jsl.platform.events.v1.TenantDeactivatedH\x00R\x11tenantDeactivated\x12H\n" +
	"\fsite_created\x18\x18 \x01(\v2#.jsl.platform.events.v1.SiteCreatedH\x00R\vsiteCreated\x12g\n" +
	"\x17industry_assembly_bound\x18\x19 \x01(\v2-.jsl.platform.events.v1.IndustryAssemblyBoundH\x00R\x15industryAssemblyBoundB\b\n" +
	"\x06events\"\xf3\x01\n" +
	"\x11TenantProvisioned\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\aplan_id\x18\x03 \x01(\tR\x06planId\x12'\n" +
	"\x0fisolation_level\x18\x04 \x01(\tR\x0eisolationLevel\x12)\n" +
	"\x10industry_modules\x18\x05 \x03(\tR\x0findustryModules\x12\x1e\n" +
	"\vroot_org_id\x18\x06 \x01(\tR\trootOrgId\x12 \n" +
	"\froot_site_id\x18\a \x01(\tR\n" +
	"rootSiteId\"F\n" +
	"\x0fTenantSuspended\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"0\n" +
	"\x11TenantReactivated\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"H\n" +
	"\x11TenantDeactivated\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"}\n" +
	"\vSiteCreated\x12\x17\n" +
	"\asite_id\x18\x01 \x01(\tR\x06siteId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12$\n" +
	"\x0eparent_site_id\x18\x03 \x01(\tR\fparentSiteId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"x\n" +
	"\x15IndustryAssemblyBound\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\tmodule_id\x18\x02 \x01(\tR\bmoduleId\x12%\n" +
	"\x0emodule_version\x18\x03 \x01(\tR\rmoduleVersionB5Z3github.com/jsl-aiot/platform/api/events/v1;eventsv1b\x06proto3"

var (
	file_events_v1_envelope_proto_rawDescOnce sync.Once
	file_events_v1_envelope_proto_rawDescData []byte
)

func file_events_v1_envelope_proto_rawDescGZIP() []byte {
	file_events_v1_envelope_proto_rawDescOnce.Do(func() {
		file_events_v1_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_v1_envelope_proto_rawDesc), len(file_events_v1_envelope_proto_rawDesc)))
	})
	return file_events_v1_envelope_proto_rawDescData
}

var file_events_v1_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_events_v1_envelope_proto_goTypes = []any{
	(*EventEnvelope)(nil),         // 0: jsl.platform.events.v1.EventEnvelope
	(*TenantProvisioned)(nil),     // 1: jsl.platform.events.v1.TenantProvisioned
	(*TenantSuspended)(nil),       // 2: jsl.platform.events.v1.TenantSuspended
	(*TenantReactivated)(nil),     // 3: jsl.platform.events.v1.TenantReactivated
	(*TenantDeactivated)(nil),     // 4: jsl.platform.events.v1.TenantDeactivated
	(*SiteCreated)(nil),           // 5: jsl.platform.events.v1.SiteCreated
	(*IndustryAssemblyBound)(nil), // 6: jsl.platform.events.v1.IndustryAssemblyBound
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_events_v1_envelope_proto_depIdxs = []int32{
	7, // 0: jsl.platform.events.v1.EventEnvelope.occurred_at:type_name -> google.protobuf.Timestamp
	1, // 1: jsl.platform.events.v1.EventEnvelope.tenant_provisioned:type_name -> jsl.platform.events.v1.TenantProvisioned
	2, // 2: jsl.platform.events.v1.EventEnvelope.tenant_suspended:type_name -> jsl.platform.events.v1.TenantSuspended
	3, // 3: jsl.platform.events.v1.EventEnvelope.tenant_reactivated:type_name -> jsl.platform.events.v1.TenantReactivated
	4, // 4: jsl.platform.events.v1.EventEnvelope.tenant_deactivated:type_name -> jsl.platform.events.v1.TenantDeactivated
	5, // 5: jsl.platform.events.v1.EventEnvelope.site_created:type_name -> jsl.platform.events.v1.SiteCreated
	6, // 6: jsl.platform.events.v1.EventEnvelope.industry_assembly_bound:type_name -> jsl.platform.events.v1.IndustryAssemblyBound
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_events_v1_envelope_proto_init() }
func file_events_v1_envelope_proto_init() {
	if File_events_v1_envelope_proto != nil {
		return
	}
	file_events_v1_envelope_proto_msgTypes[0].OneofWrappers = []any{
		(*EventEnvelope_TenantProvisioned)(nil),
		(*EventEnvelope_TenantSuspended)(nil),
		(*EventEnvelope_TenantReactivated)(nil),
		(*EventEnvelope_TenantDeactivated)(nil),
		(*EventEnvelope_SiteCreated)(nil),
		(*EventEnvelope_IndustryAssemblyBound)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_v1_envelope_proto_rawDesc), len(file_events_v1_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_v1_envelope_proto_goTypes,
		DependencyIndexes: file_events_v1_envelope_proto_depIdxs,
		MessageInfos:      file_events_v1_envelope_proto_msgTypes,
	}.Build()
	File_events_v1_envelope_proto = out.File
	file_events_v1_envelope_proto_goTypes = nil
	file_events_v1_envelope_proto_depIdxs = nil
}
