// BC-P1 组织契约。组织树挂在租户之下，根组织由租户开通时初始化；
// 新组织必须挂在租户根（parent 为空）或既有组织之下。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: org/v1/org.proto

package orgv1

import (
	v1 "github.com/jsl-aiot/platform/api/common/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Organization 组织聚合。
type Organization struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	OrgId    string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	TenantId string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// 父组织，为空表示挂在租户根。
	ParentOrgId string `protobuf:"bytes,3,opt,name=parent_org_id,json=parentOrgId,proto3" json:"parent_org_id,omitempty"`
	// 组织内唯一。
	Name          string          `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName   string          `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Audit         *v1.AuditFields `protobuf:"bytes,6,opt,name=audit,proto3" json:"audit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Organization) Reset() {
	*x = Organization{}
	mi := &file_org_v1_org_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Organization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Organization) ProtoMessage() {}

func (x *Organization) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Organization.ProtoReflect.Descriptor instead.
func (*Organization) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{0}
}

func (x *Organization) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *Organization) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Organization) GetParentOrgId() string {
	if x != nil {
		return x.ParentOrgId
	}
	return ""
}

func (x *Organization) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Organization) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Organization) GetAudit() *v1.AuditFields {
	if x != nil {
		return x.Audit
	}
	return nil
}

type CreateOrgRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentOrgId   string                 `protobuf:"bytes,1,opt,name=parent_org_id,json=parentOrgId,proto3" json:"parent_org_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrgRequest) Reset() {
	*x = CreateOrgRequest{}
	mi := &file_org_v1_org_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrgRequest) ProtoMessage() {}

func (x *CreateOrgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrgRequest.ProtoReflect.Descriptor instead.
func (*CreateOrgRequest) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrgRequest) GetParentOrgId() string {
	if x != nil {
		return x.ParentOrgId
	}
	return ""
}

func (x *CreateOrgRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateOrgRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type GetOrgRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrgRequest) Reset() {
	*x = GetOrgRequest{}
	mi := &file_org_v1_org_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrgRequest) ProtoMessage() {}

func (x *GetOrgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrgRequest.ProtoReflect.Descriptor instead.
func (*GetOrgRequest) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{2}
}

func (x *GetOrgRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

type ListOrgsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *v1.PageRequest        `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrgsRequest) Reset() {
	*x = ListOrgsRequest{}
	mi := &file_org_v1_org_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrgsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrgsRequest) ProtoMessage() {}

func (x *ListOrgsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrgsRequest.ProtoReflect.Descriptor instead.
func (*ListOrgsRequest) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{3}
}

func (x *ListOrgsRequest) GetPage() *v1.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListOrgsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orgs          []*Organization        `protobuf:"bytes,1,rep,name=orgs,proto3" json:"orgs,omitempty"`
	Page          *v1.PageResponse       `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrgsResponse) Reset() {
	*x = ListOrgsResponse{}
	mi := &file_org_v1_org_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrgsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrgsResponse) ProtoMessage() {}

func (x *ListOrgsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrgsResponse.ProtoReflect.Descriptor instead.
func (*ListOrgsResponse) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{4}
}

func (x *ListOrgsResponse) GetOrgs() []*Organization {
	if x != nil {
		return x.Orgs
	}
	return nil
}

func (x *ListOrgsResponse) GetPage() *v1.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type UpdateOrgRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrgRequest) Reset() {
	*x = UpdateOrgRequest{}
	mi := &file_org_v1_org_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrgRequest) ProtoMessage() {}

func (x *UpdateOrgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrgRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrgRequest) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateOrgRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *UpdateOrgRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UpdateOrgRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_org_v1_org_proto protoreflect.FileDescriptor

const file_org_v1_org_proto_rawDesc = "" +
	"\n" +
	"\x10org/v1/org.proto\x12\x13jsl.platform.org.v1\x1a\x16common/v1/common.proto\x1a\x1cgoogle/api/annotations.proto\"\xd8\x01\n" +
	"\fOrganization\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\"\n" +
	"\rparent_org_id\x18\x03 \x01(\tR\vparentOrgId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x05 \x01(\tR\vdisplayName\x129\n" +
	"\x05audit\x18\x06 \x01(\v2#.jsl.platform.common.v1.AuditFieldsR\x05audit\"m\n" +
	"\x10CreateOrgRequest\x12\"\n" +
	"\rparent_org_id\x18\x01 \x01(\tR\vparentOrgId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\"&\n" +
	"\rGetOrgRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\"J\n" +
	"\x0fListOrgsRequest\x127\n" +
	"\x04page\x18\x01 \x01(\v2#.jsl.platform.common.v1.PageRequestR\x04page\"\x83\x01\n" +
	"\x10ListOrgsResponse\x125\n" +
	"\x04orgs\x18\x01 \x03(\v2!.jsl.platform.org.v1.OrganizationR\x04orgs\x128\n" +
	"\x04page\x18\x02 \x01(\v2$.jsl.platform.common.v1.PageResponseR\x04page\"f\n" +
	"\x10UpdateOrgRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion2\xc4\x03\n" +
	"\n" +
	"OrgService\x12j\n" +
	"\tCreateOrg\x12%.jsl.platform.org.v1.CreateOrgRequest\x1a!.jsl.platform.org.v1.Organization\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v1/orgs\x12j\n" +
	"\x06GetOrg\x12\".jsl.platform.org.v1.GetOrgRequest\x1a!.jsl.platform.org.v1.Organization\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/orgs/{org_id}\x12i\n" +
	"\bListOrgs\x12$.jsl.platform.org.v1.ListOrgsRequest\x1a%.jsl.platform.org.v1.ListOrgsResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/v1/orgs\x12s\n" +
	"\tUpdateOrg\x12%.jsl.platform.org.v1.UpdateOrgRequest\x1a!.jsl.platform.org.v1.Organization\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*2\x11/v1/orgs/{org_id}B/Z-github.com/jsl-aiot/platform/api/org/v1;orgv1b\x06proto3"

var (
	file_org_v1_org_proto_rawDescOnce sync.Once
	file_org_v1_org_proto_rawDescData []byte
)

func file_org_v1_org_proto_rawDescGZIP() []byte {
	file_org_v1_org_proto_rawDescOnce.Do(func() {
		file_org_v1_org_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_org_v1_org_proto_rawDesc), len(file_org_v1_org_proto_rawDesc)))
	})
	return file_org_v1_org_proto_rawDescData
}

var file_org_v1_org_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_org_v1_org_proto_goTypes = []any{
	(*Organization)(nil),     // 0: jsl.platform.org.v1.Organization
	(*CreateOrgRequest)(nil), // 1: jsl.platform.org.v1.CreateOrgRequest
	(*GetOrgRequest)(nil),    // 2: jsl.platform.org.v1.GetOrgRequest
	(*ListOrgsRequest)(nil),  // 3: jsl.platform.org.v1.ListOrgsRequest
	(*ListOrgsResponse)(nil), // 4: jsl.platform.org.v1.ListOrgsResponse
	(*UpdateOrgRequest)(nil), // 5: jsl.platform.org.v1.UpdateOrgRequest
	(*v1.AuditFields)(nil),   // 6: jsl.platform.common.v1.AuditFields
	(*v1.PageRequest)(nil),   // 7: jsl.platform.common.v1.PageRequest
	(*v1.PageResponse)(nil),  // 8: jsl.platform.common.v1.PageResponse
}
var file_org_v1_org_proto_depIdxs = []int32{
	6, // 0: jsl.platform.org.v1.Organization.audit:type_name -> jsl.platform.common.v1.AuditFields
	7, // 1: jsl.platform.org.v1.ListOrgsRequest.page:type_name -> jsl.platform.common.v1.PageRequest
	0, // 2: jsl.platform.org.v1.ListOrgsResponse.orgs:type_name -> jsl.platform.org.v1.Organization
	8, // 3: jsl.platform.org.v1.ListOrgsResponse.page:type_name -> jsl.platform.common.v1.PageResponse
	1, // 4: jsl.platform.org.v1.OrgService.CreateOrg:input_type -> jsl.platform.org.v1.CreateOrgRequest
	2, // 5: jsl.platform.org.v1.OrgService.GetOrg:input_type -> jsl.platform.org.v1.GetOrgRequest
	3, // 6: jsl.platform.org.v1.OrgService.ListOrgs:input_type -> jsl.platform.org.v1.ListOrgsRequest
	5, // 7: jsl.platform.org.v1.OrgService.UpdateOrg:input_type -> jsl.platform.org.v1.UpdateOrgRequest
	0, // 8: jsl.platform.org.v1.OrgService.CreateOrg:output_type -> jsl.platform.org.v1.Organization
	0, // 9: jsl.platform.org.v1.OrgService.GetOrg:output_type -> jsl.platform.org.v1.Organization
	4, // 10: jsl.platform.org.v1.OrgService.ListOrgs:output_type -> jsl.platform.org.v1.ListOrgsResponse
	0, // 11: jsl.platform.org.v1.OrgService.UpdateOrg:output_type -> jsl.platform.org.v1.Organization
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_org_v1_org_proto_init() }
func file_org_v1_org_proto_init() {
	if File_org_v1_org_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_org_v1_org_proto_rawDesc), len(file_org_v1_org_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_org_v1_org_proto_goTypes,
		DependencyIndexes: file_org_v1_org_proto_depIdxs,
		MessageInfos:      file_org_v1_org_proto_msgTypes,
	}.Build()
	File_org_v1_org_proto = out.File
	file_org_v1_org_proto_goTypes = nil
	file_org_v1_org_proto_depIdxs = nil
}
