// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v3.0.0
// - protoc             (unknown)
// source: org/v1/org.proto

package orgv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationOrgServiceCreateOrg = "/jsl.platform.org.v1.OrgService/CreateOrg"
const OperationOrgServiceGetOrg = "/jsl.platform.org.v1.OrgService/GetOrg"
const OperationOrgServiceListOrgs = "/jsl.platform.org.v1.OrgService/ListOrgs"
const OperationOrgServiceUpdateOrg = "/jsl.platform.org.v1.OrgService/UpdateOrg"

type OrgServiceHTTPServer interface {
	CreateOrg(context.Context, *CreateOrgRequest) (*Organization, error)
	GetOrg(context.Context, *GetOrgRequest) (*Organization, error)
	ListOrgs(context.Context, *ListOrgsRequest) (*ListOrgsResponse, error)
	UpdateOrg(context.Context, *UpdateOrgRequest) (*Organization, error)
}

func RegisterOrgServiceHTTPServer(s *http.Server, srv OrgServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/v1/orgs", _OrgService_CreateOrg0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/orgs/{org_id}", _OrgService_GetOrg0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/orgs", _OrgService_ListOrgs0_HTTP_Handler(srv))
	r.Handle("PATCH", "/v1/orgs/{org_id}", _OrgService_UpdateOrg0_HTTP_Handler(srv))
}

func _OrgService_CreateOrg0_HTTP_Handler(srv OrgServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateOrgRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrgServiceCreateOrg)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateOrg(ctx, req.(*CreateOrgRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Organization)
		return ctx.Result(200, reply)
	}
}

func _OrgService_GetOrg0_HTTP_Handler(srv OrgServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetOrgRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrgServiceGetOrg)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetOrg(ctx, req.(*GetOrgRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Organization)
		return ctx.Result(200, reply)
	}
}

func _OrgService_ListOrgs0_HTTP_Handler(srv OrgServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListOrgsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrgServiceListOrgs)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListOrgs(ctx, req.(*ListOrgsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListOrgsResponse)
		return ctx.Result(200, reply)
	}
}

func _OrgService_UpdateOrg0_HTTP_Handler(srv OrgServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateOrgRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrgServiceUpdateOrg)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateOrg(ctx, req.(*UpdateOrgRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Organization)
		return ctx.Result(200, reply)
	}
}

type OrgServiceHTTPClient interface {
	CreateOrg(ctx context.Context, req *CreateOrgRequest, opts ...http.CallOption) (rsp *Organization, err error)
	GetOrg(ctx context.Context, req *GetOrgRequest, opts ...http.CallOption) (rsp *Organization, err error)
	ListOrgs(ctx context.Context, req *ListOrgsRequest, opts ...http.CallOption) (rsp *ListOrgsResponse, err error)
	UpdateOrg(ctx context.Context, req *UpdateOrgRequest, opts ...http.CallOption) (rsp *Organization, err error)
}

type OrgServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewOrgServiceHTTPClient(client *http.Client) OrgServiceHTTPClient {
	return &OrgServiceHTTPClientImpl{client}
}

func (c *OrgServiceHTTPClientImpl) CreateOrg(ctx context.Context, in *CreateOrgRequest, opts ...http.CallOption) (*Organization, error) {
	var out Organization
	pattern := "/v1/orgs"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationOrgServiceCreateOrg),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrgServiceHTTPClientImpl) GetOrg(ctx context.Context, in *GetOrgRequest, opts ...http.CallOption) (*Organization, error) {
	var out Organization
	pattern := "/v1/orgs/{org_id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationOrgServiceGetOrg),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrgServiceHTTPClientImpl) ListOrgs(ctx context.Context, in *ListOrgsRequest, opts ...http.CallOption) (*ListOrgsResponse, error) {
	var out ListOrgsResponse
	pattern := "/v1/orgs"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationOrgServiceListOrgs),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrgServiceHTTPClientImpl) UpdateOrg(ctx context.Context, in *UpdateOrgRequest, opts ...http.CallOption) (*Organization, error) {
	var out Organization
	pattern := "/v1/orgs/{org_id}"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationOrgServiceUpdateOrg),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
