// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v3.0.0
// - protoc             (unknown)
// source: tenant/v1/tenant.proto

package tenantv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationTenantServiceBindIndustryAssembly = "/jsl.platform.tenant.v1.TenantService/BindIndustryAssembly"
const OperationTenantServiceCreateTenant = "/jsl.platform.tenant.v1.TenantService/CreateTenant"
const OperationTenantServiceDeactivateTenant = "/jsl.platform.tenant.v1.TenantService/DeactivateTenant"
const OperationTenantServiceGetTenant = "/jsl.platform.tenant.v1.TenantService/GetTenant"
const OperationTenantServiceListIndustryAssemblies = "/jsl.platform.tenant.v1.TenantService/ListIndustryAssemblies"
const OperationTenantServiceReactivateTenant = "/jsl.platform.tenant.v1.TenantService/ReactivateTenant"
const OperationTenantServiceSuspendTenant = "/jsl.platform.tenant.v1.TenantService/SuspendTenant"

type TenantServiceHTTPServer interface {
	// BindIndustryAssembly BindIndustryAssembly 绑定行业模块装配（M4 追加）。
	BindIndustryAssembly(context.Context, *BindIndustryAssemblyRequest) (*IndustryAssembly, error)
	// CreateTenant CreateTenant 开通租户（同事务完成：租户 + 默认套餐订阅 + 装配记录初始化）。
	CreateTenant(context.Context, *CreateTenantRequest) (*Tenant, error)
	// DeactivateTenant DeactivateTenant 注销租户（仅 SUSPENDED 可进入；保留期内可人工恢复）。
	DeactivateTenant(context.Context, *DeactivateTenantRequest) (*Tenant, error)
	GetTenant(context.Context, *GetTenantRequest) (*Tenant, error)
	ListIndustryAssemblies(context.Context, *ListIndustryAssembliesRequest) (*ListIndustryAssembliesResponse, error)
	ReactivateTenant(context.Context, *ReactivateTenantRequest) (*Tenant, error)
	// SuspendTenant SuspendTenant 冻结租户（ACTIVE→SUSPENDED），产生写冻结。
	SuspendTenant(context.Context, *SuspendTenantRequest) (*Tenant, error)
}

func RegisterTenantServiceHTTPServer(s *http.Server, srv TenantServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/v1/tenants", _TenantService_CreateTenant0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/tenants/{tenant_id}", _TenantService_GetTenant0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/tenants/{tenant_id}:suspend", _TenantService_SuspendTenant0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/tenants/{tenant_id}:reactivate", _TenantService_ReactivateTenant0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/tenants/{tenant_id}:deactivate", _TenantService_DeactivateTenant0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/tenants/{tenant_id}/assemblies", _TenantService_BindIndustryAssembly0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/tenants/{tenant_id}/assemblies", _TenantService_ListIndustryAssemblies0_HTTP_Handler(srv))
}

func _TenantService_CreateTenant0_HTTP_Handler(srv TenantServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateTenantRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTenantServiceCreateTenant)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateTenant(ctx, req.(*CreateTenantRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Tenant)
		return ctx.Result(200, reply)
	}
}

func _TenantService_GetTenant0_HTTP_Handler(srv TenantServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetTenantRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTenantServiceGetTenant)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTenant(ctx, req.(*GetTenantRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Tenant)
		return ctx.Result(200, reply)
	}
}

func _TenantService_SuspendTenant0_HTTP_Handler(srv TenantServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SuspendTenantRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTenantServiceSuspendTenant)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SuspendTenant(ctx, req.(*SuspendTenantRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Tenant)
		return ctx.Result(200, reply)
	}
}

func _TenantService_ReactivateTenant0_HTTP_Handler(srv TenantServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ReactivateTenantRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTenantServiceReactivateTenant)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ReactivateTenant(ctx, req.(*ReactivateTenantRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Tenant)
		return ctx.Result(200, reply)
	}
}

func _TenantService_DeactivateTenant0_HTTP_Handler(srv TenantServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeactivateTenantRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTenantServiceDeactivateTenant)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeactivateTenant(ctx, req.(*DeactivateTenantRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Tenant)
		return ctx.Result(200, reply)
	}
}

func _TenantService_BindIndustryAssembly0_HTTP_Handler(srv TenantServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BindIndustryAssemblyRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTenantServiceBindIndustryAssembly)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BindIndustryAssembly(ctx, req.(*BindIndustryAssemblyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*IndustryAssembly)
		return ctx.Result(200, reply)
	}
}

func _TenantService_ListIndustryAssemblies0_HTTP_Handler(srv TenantServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListIndustryAssembliesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTenantServiceListIndustryAssemblies)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListIndustryAssemblies(ctx, req.(*ListIndustryAssembliesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListIndustryAssembliesResponse)
		return ctx.Result(200, reply)
	}
}

type TenantServiceHTTPClient interface {
	// BindIndustryAssembly BindIndustryAssembly 绑定行业模块装配（M4 追加）。
	BindIndustryAssembly(ctx context.Context, req *BindIndustryAssemblyRequest, opts ...http.CallOption) (rsp *IndustryAssembly, err error)
	// CreateTenant CreateTenant 开通租户（同事务完成：租户 + 默认套餐订阅 + 装配记录初始化）。
	CreateTenant(ctx context.Context, req *CreateTenantRequest, opts ...http.CallOption) (rsp *Tenant, err error)
	// DeactivateTenant DeactivateTenant 注销租户（仅 SUSPENDED 可进入；保留期内可人工恢复）。
	DeactivateTenant(ctx context.Context, req *DeactivateTenantRequest, opts ...http.CallOption) (rsp *Tenant, err error)
	GetTenant(ctx context.Context, req *GetTenantRequest, opts ...http.CallOption) (rsp *Tenant, err error)
	ListIndustryAssemblies(ctx context.Context, req *ListIndustryAssembliesRequest, opts ...http.CallOption) (rsp *ListIndustryAssembliesResponse, err error)
	ReactivateTenant(ctx context.Context, req *ReactivateTenantRequest, opts ...http.CallOption) (rsp *Tenant, err error)
	// SuspendTenant SuspendTenant 冻结租户（ACTIVE→SUSPENDED），产生写冻结。
	SuspendTenant(ctx context.Context, req *SuspendTenantRequest, opts ...http.CallOption) (rsp *Tenant, err error)
}

type TenantServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewTenantServiceHTTPClient(client *http.Client) TenantServiceHTTPClient {
	return &TenantServiceHTTPClientImpl{client}
}

// BindIndustryAssembly BindIndustryAssembly 绑定行业模块装配（M4 追加）。
func (c *TenantServiceHTTPClientImpl) BindIndustryAssembly(ctx context.Context, in *BindIndustryAssemblyRequest, opts ...http.CallOption) (*IndustryAssembly, error) {
	var out IndustryAssembly
	pattern := "/v1/tenants/{tenant_id}/assemblies"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationTenantServiceBindIndustryAssembly),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateTenant CreateTenant 开通租户（同事务完成：租户 + 默认套餐订阅 + 装配记录初始化）。
func (c *TenantServiceHTTPClientImpl) CreateTenant(ctx context.Context, in *CreateTenantRequest, opts ...http.CallOption) (*Tenant, error) {
	var out Tenant
	pattern := "/v1/tenants"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationTenantServiceCreateTenant),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeactivateTenant DeactivateTenant 注销租户（仅 SUSPENDED 可进入；保留期内可人工恢复）。
func (c *TenantServiceHTTPClientImpl) DeactivateTenant(ctx context.Context, in *DeactivateTenantRequest, opts ...http.CallOption) (*Tenant, error) {
	var out Tenant
	pattern := "/v1/tenants/{tenant_id}:deactivate"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationTenantServiceDeactivateTenant),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TenantServiceHTTPClientImpl) GetTenant(ctx context.Context, in *GetTenantRequest, opts ...http.CallOption) (*Tenant, error) {
	var out Tenant
	pattern := "/v1/tenants/{tenant_id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationTenantServiceGetTenant),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TenantServiceHTTPClientImpl) ListIndustryAssemblies(ctx context.Context, in *ListIndustryAssembliesRequest, opts ...http.CallOption) (*ListIndustryAssembliesResponse, error) {
	var out ListIndustryAssembliesResponse
	pattern := "/v1/tenants/{tenant_id}/assemblies"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationTenantServiceListIndustryAssemblies),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TenantServiceHTTPClientImpl) ReactivateTenant(ctx context.Context, in *ReactivateTenantRequest, opts ...http.CallOption) (*Tenant, error) {
	var out Tenant
	pattern := "/v1/tenants/{tenant_id}:reactivate"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationTenantServiceReactivateTenant),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SuspendTenant SuspendTenant 冻结租户（ACTIVE→SUSPENDED），产生写冻结。
func (c *TenantServiceHTTPClientImpl) SuspendTenant(ctx context.Context, in *SuspendTenantRequest, opts ...http.CallOption) (*Tenant, error) {
	var out Tenant
	pattern := "/v1/tenants/{tenant_id}:suspend"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationTenantServiceSuspendTenant),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
