// BC-P1 租户契约。状态机（BP-01 §4.2）：
// 创建即 ACTIVE（Provision 语义）；ACTIVE→SUSPENDED；SUSPENDED→ACTIVE；
// 注销仅可自 SUSPENDED 进入，进入 DEACTIVATED 后终态。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: tenant/v1/tenant.proto

package tenantv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TenantService_CreateTenant_FullMethodName           = "/jsl.platform.tenant.v1.TenantService/CreateTenant"
	TenantService_GetTenant_FullMethodName              = "/jsl.platform.tenant.v1.TenantService/GetTenant"
	TenantService_SuspendTenant_FullMethodName          = "/jsl.platform.tenant.v1.TenantService/SuspendTenant"
	TenantService_ReactivateTenant_FullMethodName       = "/jsl.platform.tenant.v1.TenantService/ReactivateTenant"
	TenantService_DeactivateTenant_FullMethodName       = "/jsl.platform.tenant.v1.TenantService/DeactivateTenant"
	TenantService_BindIndustryAssembly_FullMethodName   = "/jsl.platform.tenant.v1.TenantService/BindIndustryAssembly"
	TenantService_ListIndustryAssemblies_FullMethodName = "/jsl.platform.tenant.v1.TenantService/ListIndustryAssemblies"
)

// TenantServiceClient is the client API for TenantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TenantServiceClient interface {
	// CreateTenant 开通租户（同事务完成：租户 + 默认套餐订阅 + 装配记录初始化）。
	CreateTenant(ctx context.Context, in *CreateTenantRequest, opts ...grpc.CallOption) (*Tenant, error)
	GetTenant(ctx context.Context, in *GetTenantRequest, opts ...grpc.CallOption) (*Tenant, error)
	// SuspendTenant 冻结租户（ACTIVE→SUSPENDED），产生写冻结。
	SuspendTenant(ctx context.Context, in *SuspendTenantRequest, opts ...grpc.CallOption) (*Tenant, error)
	ReactivateTenant(ctx context.Context, in *ReactivateTenantRequest, opts ...grpc.CallOption) (*Tenant, error)
	// DeactivateTenant 注销租户（仅 SUSPENDED 可进入；保留期内可人工恢复）。
	DeactivateTenant(ctx context.Context, in *DeactivateTenantRequest, opts ...grpc.CallOption) (*Tenant, error)
	// BindIndustryAssembly 绑定行业模块装配（M4 追加）。
	BindIndustryAssembly(ctx context.Context, in *BindIndustryAssemblyRequest, opts ...grpc.CallOption) (*IndustryAssembly, error)
	ListIndustryAssemblies(ctx context.Context, in *ListIndustryAssembliesRequest, opts ...grpc.CallOption) (*ListIndustryAssembliesResponse, error)
}

type tenantServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTenantServiceClient(cc grpc.ClientConnInterface) TenantServiceClient {
	return &tenantServiceClient{cc}
}

func (c *tenantServiceClient) CreateTenant(ctx context.Context, in *CreateTenantRequest, opts ...grpc.CallOption) (*Tenant, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Tenant)
	err := c.cc.Invoke(ctx, TenantService_CreateTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) GetTenant(ctx context.Context, in *GetTenantRequest, opts ...grpc.CallOption) (*Tenant, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Tenant)
	err := c.cc.Invoke(ctx, TenantService_GetTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) SuspendTenant(ctx context.Context, in *SuspendTenantRequest, opts ...grpc.CallOption) (*Tenant, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Tenant)
	err := c.cc.Invoke(ctx, TenantService_SuspendTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) ReactivateTenant(ctx context.Context, in *ReactivateTenantRequest, opts ...grpc.CallOption) (*Tenant, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Tenant)
	err := c.cc.Invoke(ctx, TenantService_ReactivateTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) DeactivateTenant(ctx context.Context, in *DeactivateTenantRequest, opts ...grpc.CallOption) (*Tenant, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Tenant)
	err := c.cc.Invoke(ctx, TenantService_DeactivateTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) BindIndustryAssembly(ctx context.Context, in *BindIndustryAssemblyRequest, opts ...grpc.CallOption) (*IndustryAssembly, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IndustryAssembly)
	err := c.cc.Invoke(ctx, TenantService_BindIndustryAssembly_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) ListIndustryAssemblies(ctx context.Context, in *ListIndustryAssembliesRequest, opts ...grpc.CallOption) (*ListIndustryAssembliesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListIndustryAssembliesResponse)
	err := c.cc.Invoke(ctx, TenantService_ListIndustryAssemblies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TenantServiceServer is the server API for TenantService service.
// All implementations should embed UnimplementedTenantServiceServer
// for forward compatibility.
type TenantServiceServer interface {
	// CreateTenant 开通租户（同事务完成：租户 + 默认套餐订阅 + 装配记录初始化）。
	CreateTenant(context.Context, *CreateTenantRequest) (*Tenant, error)
	GetTenant(context.Context, *GetTenantRequest) (*Tenant, error)
	// SuspendTenant 冻结租户（ACTIVE→SUSPENDED），产生写冻结。
	SuspendTenant(context.Context, *SuspendTenantRequest) (*Tenant, error)
	ReactivateTenant(context.Context, *ReactivateTenantRequest) (*Tenant, error)
	// DeactivateTenant 注销租户（仅 SUSPENDED 可进入；保留期内可人工恢复）。
	DeactivateTenant(context.Context, *DeactivateTenantRequest) (*Tenant, error)
	// BindIndustryAssembly 绑定行业模块装配（M4 追加）。
	BindIndustryAssembly(context.Context, *BindIndustryAssemblyRequest) (*IndustryAssembly, error)
	ListIndustryAssemblies(context.Context, *ListIndustryAssembliesRequest) (*ListIndustryAssembliesResponse, error)
}

// UnimplementedTenantServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTenantServiceServer struct{}

func (UnimplementedTenantServiceServer) CreateTenant(context.Context, *CreateTenantRequest) (*Tenant, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTenant not implemented")
}
func (UnimplementedTenantServiceServer) GetTenant(context.Context, *GetTenantRequest) (*Tenant, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTenant not implemented")
}
func (UnimplementedTenantServiceServer) SuspendTenant(context.Context, *SuspendTenantRequest) (*Tenant, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SuspendTenant not implemented")
}
func (UnimplementedTenantServiceServer) ReactivateTenant(context.Context, *ReactivateTenantRequest) (*Tenant, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReactivateTenant not implemented")
}
func (UnimplementedTenantServiceServer) DeactivateTenant(context.Context, *DeactivateTenantRequest) (*Tenant, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeactivateTenant not implemented")
}
func (UnimplementedTenantServiceServer) BindIndustryAssembly(context.Context, *BindIndustryAssemblyRequest) (*IndustryAssembly, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BindIndustryAssembly not implemented")
}
func (UnimplementedTenantServiceServer) ListIndustryAssemblies(context.Context, *ListIndustryAssembliesRequest) (*ListIndustryAssembliesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListIndustryAssemblies not implemented")
}
func (UnimplementedTenantServiceServer) testEmbeddedByValue() {}

// UnsafeTenantServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TenantServiceServer will
// result in compilation errors.
type UnsafeTenantServiceServer interface {
	mustEmbedUnimplementedTenantServiceServer()
}

func RegisterTenantServiceServer(s grpc.ServiceRegistrar, srv TenantServiceServer) {
	// If the following call pancis, it indicates UnimplementedTenantServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TenantService_ServiceDesc, srv)
}

func _TenantService_CreateTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).CreateTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_CreateTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).CreateTenant(ctx, req.(*CreateTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_GetTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).GetTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_GetTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).GetTenant(ctx, req.(*GetTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_SuspendTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuspendTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).SuspendTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_SuspendTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).SuspendTenant(ctx, req.(*SuspendTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_ReactivateTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReactivateTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).ReactivateTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_ReactivateTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).ReactivateTenant(ctx, req.(*ReactivateTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_DeactivateTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeactivateTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).DeactivateTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_DeactivateTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).DeactivateTenant(ctx, req.(*DeactivateTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_BindIndustryAssembly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindIndustryAssemblyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).BindIndustryAssembly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_BindIndustryAssembly_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).BindIndustryAssembly(ctx, req.(*BindIndustryAssemblyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_ListIndustryAssemblies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIndustryAssembliesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).ListIndustryAssemblies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_ListIndustryAssemblies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).ListIndustryAssemblies(ctx, req.(*ListIndustryAssembliesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TenantService_ServiceDesc is the grpc.ServiceDesc for TenantService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TenantService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jsl.platform.tenant.v1.TenantService",
	HandlerType: (*TenantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTenant",
			Handler:    _TenantService_CreateTenant_Handler,
		},
		{
			MethodName: "GetTenant",
			Handler:    _TenantService_GetTenant_Handler,
		},
		{
			MethodName: "SuspendTenant",
			Handler:    _TenantService_SuspendTenant_Handler,
		},
		{
			MethodName: "ReactivateTenant",
			Handler:    _TenantService_ReactivateTenant_Handler,
		},
		{
			MethodName: "DeactivateTenant",
			Handler:    _TenantService_DeactivateTenant_Handler,
		},
		{
			MethodName: "BindIndustryAssembly",
			Handler:    _TenantService_BindIndustryAssembly_Handler,
		},
		{
			MethodName: "ListIndustryAssemblies",
			Handler:    _TenantService_ListIndustryAssemblies_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tenant/v1/tenant.proto",
}
