// BC-P1 租户契约。状态机（BP-01 §4.2）：
// 创建即 ACTIVE（Provision 语义）；ACTIVE→SUSPENDED；SUSPENDED→ACTIVE；
// 注销仅可自 SUSPENDED 进入，进入 DEACTIVATED 后终态。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: tenant/v1/tenant.proto

package tenantv1

import (
	v1 "github.com/jsl-aiot/platform/api/common/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TenantStatus 租户生命周期状态。
type TenantStatus int32

const (
	TenantStatus_TENANT_STATUS_UNSPECIFIED TenantStatus = 0
	TenantStatus_TENANT_STATUS_ACTIVE      TenantStatus = 1
	TenantStatus_TENANT_STATUS_SUSPENDED   TenantStatus = 2
	TenantStatus_TENANT_STATUS_DEACTIVATED TenantStatus = 3
)

// Enum value maps for TenantStatus.
var (
	TenantStatus_name = map[int32]string{
		0: "TENANT_STATUS_UNSPECIFIED",
		1: "TENANT_STATUS_ACTIVE",
		2: "TENANT_STATUS_SUSPENDED",
		3: "TENANT_STATUS_DEACTIVATED",
	}
	TenantStatus_value = map[string]int32{
		"TENANT_STATUS_UNSPECIFIED": 0,
		"TENANT_STATUS_ACTIVE":      1,
		"TENANT_STATUS_SUSPENDED":   2,
		"TENANT_STATUS_DEACTIVATED": 3,
	}
)

func (x TenantStatus) Enum() *TenantStatus {
	p := new(TenantStatus)
	*p = x
	return p
}

func (x TenantStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TenantStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_tenant_v1_tenant_proto_enumTypes[0].Descriptor()
}

func (TenantStatus) Type() protoreflect.EnumType {
	return &file_tenant_v1_tenant_proto_enumTypes[0]
}

func (x TenantStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TenantStatus.Descriptor instead.
func (TenantStatus) EnumDescriptor() ([]byte, []int) {
	return file_tenant_v1_tenant_proto_rawDescGZIP(), []int{0}
}

// IsolationLevel 租户隔离级别（BP-03 §3.1）。
type IsolationLevel int32

const (
	IsolationLevel_ISOLATION_LEVEL_UNSPECIFIED IsolationLevel = 0
	// 独立数据库。
	IsolationLevel_ISOLATION_LEVEL_T1_DEDICATED IsolationLevel = 1
	// 独立 Schema。
	IsolationLevel_ISOLATION_LEVEL_T2_SCHEMA IsolationLevel = 2
	// 行级隔离（RLS）。
	IsolationLevel_ISOLATION_LEVEL_T3_ROW IsolationLevel = 3
)

// Enum value maps for IsolationLevel.
var (
	IsolationLevel_name = map[int32]string{
		0: "ISOLATION_LEVEL_UNSPECIFIED",
		1: "ISOLATION_LEVEL_T1_DEDICATED",
		2: "ISOLATION_LEVEL_T2_SCHEMA",
		3: "ISOLATION_LEVEL_T3_ROW",
	}
	IsolationLevel_value = map[string]int32{
		"ISOLATION_LEVEL_UNSPECIFIED":  0,
		"ISOLATION_LEVEL_T1_DEDICATED": 1,
		"ISOLATION_LEVEL_T2_SCHEMA":    2,
		"ISOLATION_LEVEL_T3_ROW":       3,
	}
)

func (x IsolationLevel) Enum() *IsolationLevel {
	p := new(IsolationLevel)
	*p = x
	return p
}

func (x IsolationLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IsolationLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_tenant_v1_tenant_proto_enumTypes[1].Descriptor()
}

func (IsolationLevel) Type() protoreflect.EnumType {
	return &file_tenant_v1_tenant_proto_enumTypes[1]
}

func (x IsolationLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IsolationLevel.Descriptor instead.
func (IsolationLevel) EnumDescriptor() ([]byte, []int) {
	return file_tenant_v1_tenant_proto_rawDescGZIP(), []int{1}
}

// Tenant 租户聚合。
type Tenant struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	TenantId string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// 全局唯一外部标识（小写字母数字与连字符）。
	Name        string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName string         `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Status      TenantStatus   `protobuf:"varint,4,opt,name=status,proto3,enum=jsl.platform.tenant.v1.TenantStatus" json:"status,omitempty"`
	Isolation   IsolationLevel `protobuf:"varint,5,opt,name=isolation,proto3,enum=jsl.platform.tenant.v1.IsolationLevel" json:"isolation,omitempty"`
	PlanId      string         `protobuf:"bytes,6,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	// 数据驻留区域（ADR-0009）。
	HomeRegion    string          `protobuf:"bytes,7,opt,name=home_region,json=homeRegion,proto3" json:"home_region,omitempty"`
	Audit         *v1.AuditFields `protobuf:"bytes,8,opt,name=audit,proto3" json:"audit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tenant) Reset() {
	*x = Tenant{}
	mi := &file_tenant_v1_tenant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tenant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tenant) ProtoMessage() {}

func (x *Tenant) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_tenant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tenant.ProtoReflect.Descriptor instead.
func (*Tenant) Descriptor() ([]byte, []int) {
	return file_tenant_v1_tenant_proto_rawDescGZIP(), []int{0}
}

func (x *Tenant) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Tenant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tenant) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Tenant) GetStatus() TenantStatus {
	if x != nil {
		return x.Status
	}
	return TenantStatus_TENANT_STATUS_UNSPECIFIED
}

func (x *Tenant) GetIsolation() IsolationLevel {
	if x != nil {
		return x.Isolation
	}
	return IsolationLevel_ISOLATION_LEVEL_UNSPECIFIED
}

func (x *Tenant) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *Tenant) GetHomeRegion() string {
	if x != nil {
		return x.HomeRegion
	}
	return ""
}

func (x *Tenant) GetAudit() *v1.AuditFields {
	if x != nil {
		return x.Audit
	}
	return nil
}

type CreateTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Isolation     IsolationLevel         `protobuf:"varint,3,opt,name=isolation,proto3,enum=jsl.platform.tenant.v1.IsolationLevel" json:"isolation,omitempty"`
	PlanId        string                 `protobuf:"bytes,4,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	HomeRegion    string                 `protobuf:"bytes,5,opt,name=home_region,json=homeRegion,proto3" json:"home_region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTenantRequest) Reset() {
	*x = CreateTenantRequest{}
	mi := &file_tenant_v1_tenant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTenantRequest) ProtoMessage() {}

func (x *CreateTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_tenant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTenantRequest.ProtoReflect.Descriptor instead.
func (*CreateTenantRequest) Descriptor() ([]byte, []int) {
	return file_tenant_v1_tenant_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTenantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTenantRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CreateTenantRequest) GetIsolation() IsolationLevel {
	if x != nil {
		return x.Isolation
	}
	return IsolationLevel_ISOLATION_LEVEL_UNSPECIFIED
}

func (x *CreateTenantRequest) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *CreateTenantRequest) GetHomeRegion() string {
	if x != nil {
		return x.HomeRegion
	}
	return ""
}

type GetTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantRequest) Reset() {
	*x = GetTenantRequest{}
	mi := &file_tenant_v1_tenant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantRequest) ProtoMessage() {}

func (x *GetTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_tenant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantRequest.ProtoReflect.Descriptor instead.
func (*GetTenantRequest) Descriptor() ([]byte, []int) {
	return file_tenant_v1_tenant_proto_rawDescGZIP(), []int{2}
}

func (x *GetTenantRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type SuspendTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspendTenantRequest) Reset() {
	*x = SuspendTenantRequest{}
	mi := &file_tenant_v1_tenant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspendTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendTenantRequest) ProtoMessage() {}

func (x *SuspendTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_tenant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendTenantRequest.ProtoReflect.Descriptor instead.
func (*SuspendTenantRequest) Descriptor() ([]byte, []int) {
	return file_tenant_v1_tenant_proto_rawDescGZIP(), []int{3}
}

func (x *SuspendTenantRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SuspendTenantRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ReactivateTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReactivateTenantRequest) Reset() {
	*x = ReactivateTenantRequest{}
	mi := &file_tenant_v1_tenant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactivateTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactivateTenantRequest) ProtoMessage() {}

func (x *ReactivateTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_tenant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactivateTenantRequest.ProtoReflect.Descriptor instead.
func (*ReactivateTenantRequest) Descriptor() ([]byte, []int) {
	return file_tenant_v1_tenant_proto_rawDescGZIP(), []int{4}
}

func (x *ReactivateTenantRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type DeactivateTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateTenantRequest) Reset() {
	*x = DeactivateTenantRequest{}
	mi := &file_tenant_v1_tenant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateTenantRequest) ProtoMessage() {}

func (x *DeactivateTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_tenant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateTenantRequest.ProtoReflect.Descriptor instead.
func (*DeactivateTenantRequest) Descriptor() ([]byte, []int) {
	return file_tenant_v1_tenant_proto_rawDescGZIP(), []int{5}
}

func (x *DeactivateTenantRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DeactivateTenantRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type BindIndustryAssemblyRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	TenantId string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// 行业模块 ID，如 "industry.building"。
	ModuleId string `protobuf:"bytes,2,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	// 模块版本（semver）。
	ModuleVersion string `protobuf:"bytes,3,opt,name=module_version,json=moduleVersion,proto3" json:"module_version,omitempty"`
	Enabled       bool   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindIndustryAssemblyRequest) Reset() {
	*x = BindIndustryAssemblyRequest{}
	mi := &file_tenant_v1_tenant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindIndustryAssemblyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindIndustryAssemblyRequest) ProtoMessage() {}

func (x *BindIndustryAssemblyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_tenant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindIndustryAssemblyRequest.ProtoReflect.Descriptor instead.
func (*BindIndustryAssemblyRequest) Descriptor() ([]byte, []int) {
	return file_tenant_v1_tenant_proto_rawDescGZIP(), []int{6}
}

func (x *BindIndustryAssemblyRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *BindIndustryAssemblyRequest) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

func (x *BindIndustryAssemblyRequest) GetModuleVersion() string {
	if x != nil {
		return x.ModuleVersion
	}
	return ""
}

func (x *BindIndustryAssemblyRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// IndustryAssembly 行业模块装配记录。
type IndustryAssembly struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModuleId      string                 `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	ModuleVersion string                 `protobuf:"bytes,2,opt,name=module_version,json=moduleVersion,proto3" json:"module_version,omitempty"`
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Audit         *v1.AuditFields        `protobuf:"bytes,4,opt,name=audit,proto3" json:"audit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndustryAssembly) Reset() {
	*x = IndustryAssembly{}
	mi := &file_tenant_v1_tenant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndustryAssembly) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndustryAssembly) ProtoMessage() {}

func (x *IndustryAssembly) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_tenant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndustryAssembly.ProtoReflect.Descriptor instead.
func (*IndustryAssembly) Descriptor() ([]byte, []int) {
	return file_tenant_v1_tenant_proto_rawDescGZIP(), []int{7}
}

func (x *IndustryAssembly) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

func (x *IndustryAssembly) GetModuleVersion() string {
	if x != nil {
		return x.ModuleVersion
	}
	return ""
}

func (x *IndustryAssembly) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *IndustryAssembly) GetAudit() *v1.AuditFields {
	if x != nil {
		return x.Audit
	}
	return nil
}

type ListIndustryAssembliesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIndustryAssembliesRequest) Reset() {
	*x = ListIndustryAssembliesRequest{}
	mi := &file_tenant_v1_tenant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIndustryAssembliesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIndustryAssembliesRequest) ProtoMessage() {}

func (x *ListIndustryAssembliesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_tenant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIndustryAssembliesRequest.ProtoReflect.Descriptor instead.
func (*ListIndustryAssembliesRequest) Descriptor() ([]byte, []int) {
	return file_tenant_v1_tenant_proto_rawDescGZIP(), []int{8}
}

func (x *ListIndustryAssembliesRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type ListIndustryAssembliesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assemblies    []*IndustryAssembly    `protobuf:"bytes,1,rep,name=assemblies,proto3" json:"assemblies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIndustryAssembliesResponse) Reset() {
	*x = ListIndustryAssembliesResponse{}
	mi := &file_tenant_v1_tenant_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIndustryAssembliesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIndustryAssembliesResponse) ProtoMessage() {}

func (x *ListIndustryAssembliesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_tenant_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIndustryAssembliesResponse.ProtoReflect.Descriptor instead.
func (*ListIndustryAssembliesResponse) Descriptor() ([]byte, []int) {
	return file_tenant_v1_tenant_proto_rawDescGZIP(), []int{9}
}

func (x *ListIndustryAssembliesResponse) GetAssemblies() []*IndustryAssembly {
	if x != nil {
		return x.Assemblies
	}
	return nil
}

var File_tenant_v1_tenant_proto protoreflect.FileDescriptor

const file_tenant_v1_tenant_proto_rawDesc = "" +
	"\n" +
	"\x16tenant/v1/tenant.proto\x12\x16jsl.platform.tenant.v1\x1a\x16common/v1/common.proto\x1a\x1cgoogle/api/annotations.proto\"\xd5\x02\n" +
	"\x06Tenant\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12<\n" +
	"\x06status\x18\x04 \x01(\x0e2$.jsl.platform.tenant.v1.TenantStatusR\x06status\x12D\n" +
	"\tisolation\x18\x05 \x01(\x0e2&.jsl.platform.tenant.v1.IsolationLevelR\tisolation\x12\x17\n" +
	"\aplan_id\x18\x06 \x01(\tR\x06planId\x12\x1f\n" +
	"\vhome_region\x18\a \x01(\tR\n" +
	"homeRegion\x129\n" +
	"\x05audit\x18\b \x01(\v2#.jsl.platform.common.v1.AuditFieldsR\x05audit\"\xcc\x01\n" +
	"\x13CreateTenantRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12D\n" +
	"\tisolation\x18\x03 \x01(\x0e2&.jsl.platform.tenant.v1.IsolationLevelR\tisolation\x12\x17\n" +
	"\aplan_id\x18\x04 \x01(\tR\x06planId\x12\x1f\n" +
	"\vhome_region\x18\x05 \x01(\tR\n" +
	"homeRegion\"/\n" +
	"\x10GetTenantRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"K\n" +
	"\x14SuspendTenantRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"6\n" +
	"\x17ReactivateTenantRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"N\n" +
	"\x17DeactivateTenantRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x98\x01\n" +
	"\x1bBindIndustryAssemblyRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\tmodule_id\x18\x02 \x01(\tR\bmoduleId\x12%\n" +
	"\x0emodule_version\x18\x03 \x01(\tR\rmoduleVersion\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\"\xab\x01\n" +
	"\x10IndustryAssembly\x12\x1b\n" +
	"\tmodule_id\x18\x01 \x01(\tR\bmoduleId\x12%\n" +
	"\x0emodule_version\x18\x02 \x01(\tR\rmoduleVersion\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x129\n" +
	"\x05audit\x18\x04 \x01(\v2#.jsl.platform.common.v1.AuditFieldsR\x05audit\"<\n" +
	"\x1dListIndustryAssembliesRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"j\n" +
	"\x1eListIndustryAssembliesResponse\x12H\n" +
	"\n" +
	"assemblies\x18\x01 \x03(\v2(.jsl.platform.tenant.v1.IndustryAssemblyR\n" +
	"assemblies*\x83\x01\n" +
	"\fTenantStatus\x12\x1d\n" +
	"\x19TENANT_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14TENANT_STATUS_ACTIVE\x10\x01\x12\x1b\n" +
	"\x17TENANT_STATUS_SUSPENDED\x10\x02\x12\x1d\n" +
	"\x19TENANT_STATUS_DEACTIVATED\x10\x03*\x8e\x01\n" +
	"\x0eIsolationLevel\x12\x1f\n" +
	"\x1bISOLATION_LEVEL_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cISOLATION_LEVEL_T1_DEDICATED\x10\x01\x12\x1d\n" +
	"\x19ISOLATION_LEVEL_T2_SCHEMA\x10\x02\x12\x1a\n" +
	"\x16ISOLATION_LEVEL_T3_ROW\x10\x032\x8f\b\n" +
	"\rTenantService\x12s\n" +
	"\fCreateTenant\x12+.jsl.platform.tenant.v1.CreateTenantRequest\x1a\x1e.jsl.platform.tenant.v1.Tenant\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/tenants\x12v\n" +
	"\tGetTenant\x12(.jsl.platform.tenant.v1.GetTenantRequest\x1a\x1e.jsl.platform.tenant.v1.Tenant\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/tenants/{tenant_id}\x12\x89\x01\n" +
	"\rSuspendTenant\x12,.jsl.platform.tenant.v1.SuspendTenantRequest\x1a\x1e.jsl.platform.tenant.v1.Tenant\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/tenants/{tenant_id}:suspend\x12\x92\x01\n" +
	"\x10ReactivateTenant\x12/.jsl.platform.tenant.v1.ReactivateTenantRequest\x1a\x1e.jsl.platform.tenant.v1.Tenant\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/v1/tenants/{tenant_id}:reactivate\x12\x92\x01\n" +
	"\x10DeactivateTenant\x12/.jsl.platform.tenant.v1.DeactivateTenantRequest\x1a\x1e.jsl.platform.tenant.v1.Tenant\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/v1/tenants/{tenant_id}:deactivate\x12\xa4\x01\n" +
	"\x14BindIndustryAssembly\x123.jsl.platform.tenant.v1.BindIndustryAssemblyRequest\x1a(.jsl.platform.tenant.v1.IndustryAssembly\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/v1/tenants/{tenant_id}/assemblies\x12\xb3\x01\n" +
	"\x16ListIndustryAssemblies\x125.jsl.platform.tenant.v1.ListIndustryAssembliesRequest\x1a6.jsl.platform.tenant.v1.ListIndustryAssembliesResponse\"*\x82\xd3\xe4\x93\x02$\x12\"/v1/tenants/{tenant_id}/assembliesB5Z3github.com/jsl-aiot/platform/api/tenant/v1;tenantv1b\x06proto3"

var (
	file_tenant_v1_tenant_proto_rawDescOnce sync.Once
	file_tenant_v1_tenant_proto_rawDescData []byte
)

func file_tenant_v1_tenant_proto_rawDescGZIP() []byte {
	file_tenant_v1_tenant_proto_rawDescOnce.Do(func() {
		file_tenant_v1_tenant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tenant_v1_tenant_proto_rawDesc), len(file_tenant_v1_tenant_proto_rawDesc)))
	})
	return file_tenant_v1_tenant_proto_rawDescData
}

var file_tenant_v1_tenant_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_tenant_v1_tenant_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_tenant_v1_tenant_proto_goTypes = []any{
	(TenantStatus)(0),                      // 0: jsl.platform.tenant.v1.TenantStatus
	(IsolationLevel)(0),                    // 1: jsl.platform.tenant.v1.IsolationLevel
	(*Tenant)(nil),                         // 2: jsl.platform.tenant.v1.Tenant
	(*CreateTenantRequest)(nil),            // 3: jsl.platform.tenant.v1.CreateTenantRequest
	(*GetTenantRequest)(nil),               // 4: jsl.platform.tenant.v1.GetTenantRequest
	(*SuspendTenantRequest)(nil),           // 5: jsl.platform.tenant.v1.SuspendTenantRequest
	(*ReactivateTenantRequest)(nil),        // 6: jsl.platform.tenant.v1.ReactivateTenantRequest
	(*DeactivateTenantRequest)(nil),        // 7: jsl.platform.tenant.v1.DeactivateTenantRequest
	(*BindIndustryAssemblyRequest)(nil),    // 8: jsl.platform.tenant.v1.BindIndustryAssemblyRequest
	(*IndustryAssembly)(nil),               // 9: jsl.platform.tenant.v1.IndustryAssembly
	(*ListIndustryAssembliesRequest)(nil),  // 10: jsl.platform.tenant.v1.ListIndustryAssembliesRequest
	(*ListIndustryAssembliesResponse)(nil), // 11: jsl.platform.tenant.v1.ListIndustryAssembliesResponse
	(*v1.AuditFields)(nil),                 // 12: jsl.platform.common.v1.AuditFields
}
var file_tenant_v1_tenant_proto_depIdxs = []int32{
	0,  // 0: jsl.platform.tenant.v1.Tenant.status:type_name -> jsl.platform.tenant.v1.TenantStatus
	1,  // 1: jsl.platform.tenant.v1.Tenant.isolation:type_name -> jsl.platform.tenant.v1.IsolationLevel
	12, // 2: jsl.platform.tenant.v1.Tenant.audit:type_name -> jsl.platform.common.v1.AuditFields
	1,  // 3: jsl.platform.tenant.v1.CreateTenantRequest.isolation:type_name -> jsl.platform.tenant.v1.IsolationLevel
	12, // 4: jsl.platform.tenant.v1.IndustryAssembly.audit:type_name -> jsl.platform.common.v1.AuditFields
	9,  // 5: jsl.platform.tenant.v1.ListIndustryAssembliesResponse.assemblies:type_name -> jsl.platform.tenant.v1.IndustryAssembly
	3,  // 6: jsl.platform.tenant.v1.TenantService.CreateTenant:input_type -> jsl.platform.tenant.v1.CreateTenantRequest
	4,  // 7: jsl.platform.tenant.v1.TenantService.GetTenant:input_type -> jsl.platform.tenant.v1.GetTenantRequest
	5,  // 8: jsl.platform.tenant.v1.TenantService.SuspendTenant:input_type -> jsl.platform.tenant.v1.SuspendTenantRequest
	6,  // 9: jsl.platform.tenant.v1.TenantService.ReactivateTenant:input_type -> jsl.platform.tenant.v1.ReactivateTenantRequest
	7,  // 10: jsl.platform.tenant.v1.TenantService.DeactivateTenant:input_type -> jsl.platform.tenant.v1.DeactivateTenantRequest
	8,  // 11: jsl.platform.tenant.v1.TenantService.BindIndustryAssembly:input_type -> jsl.platform.tenant.v1.BindIndustryAssemblyRequest
	10, // 12: jsl.platform.tenant.v1.TenantService.ListIndustryAssemblies:input_type -> jsl.platform.tenant.v1.ListIndustryAssembliesRequest
	2,  // 13: jsl.platform.tenant.v1.TenantService.CreateTenant:output_type -> jsl.platform.tenant.v1.Tenant
	2,  // 14: jsl.platform.tenant.v1.TenantService.GetTenant:output_type -> jsl.platform.tenant.v1.Tenant
	2,  // 15: jsl.platform.tenant.v1.TenantService.SuspendTenant:output_type -> jsl.platform.tenant.v1.Tenant
	2,  // 16: jsl.platform.tenant.v1.TenantService.ReactivateTenant:output_type -> jsl.platform.tenant.v1.Tenant
	2,  // 17: jsl.platform.tenant.v1.TenantService.DeactivateTenant:output_type -> jsl.platform.tenant.v1.Tenant
	9,  // 18: jsl.platform.tenant.v1.TenantService.BindIndustryAssembly:output_type -> jsl.platform.tenant.v1.IndustryAssembly
	11, // 19: jsl.platform.tenant.v1.TenantService.ListIndustryAssemblies:output_type -> jsl.platform.tenant.v1.ListIndustryAssembliesResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_tenant_v1_tenant_proto_init() }
func file_tenant_v1_tenant_proto_init() {
	if File_tenant_v1_tenant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tenant_v1_tenant_proto_rawDesc), len(file_tenant_v1_tenant_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tenant_v1_tenant_proto_goTypes,
		DependencyIndexes: file_tenant_v1_tenant_proto_depIdxs,
		EnumInfos:         file_tenant_v1_tenant_proto_enumTypes,
		MessageInfos:      file_tenant_v1_tenant_proto_msgTypes,
	}.Build()
	File_tenant_v1_tenant_proto = out.File
	file_tenant_v1_tenant_proto_goTypes = nil
	file_tenant_v1_tenant_proto_depIdxs = nil
}
