apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tenant-bc.name" . }}-config
  labels:
    {{- include "tenant-bc.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
