name: contracts

on:
  push:
    branches: [master]
    paths: ["api/**"]
  pull_request:
    paths: ["api/**"]

jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v1
        with:
          input: api
          lint: true
          format: false
          breaking: true
          push: false
          breaking_against: "https://github.com/${{ github.repository }}.git#branch=master,subdir=api"
